# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

ruby '2.3.0'
# gem "rails"

gem 'sinatra'
gem 'rake'
gem 'datamapper'
gem 'dm-postgres-adapter'
gem 'database_cleaner'
gem 'pg'

gem 'capybara'
gem 'rspec'
